[package]
name = "simple-c"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/Sirius902/simple-c/"

[dependencies]
once_cell = "1.17.1"
regex = "1.8.1"
thiserror = "1.0.40"
unicode-width = "0.1.10"
